name: Prefect Flows deployment

on:
  push:
    branches:
      - staging
      - main

jobs:
  upload-prefect-deployments:
    name: Upload Prefect deployments
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    env:
      PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      PREFECT_API_URL: ${{ secrets.PREFECT_API_URL }}
    steps:
      - name: Set development environment
        if: ${{ github.ref_name == 'staging' }}
        run: |
          echo "FLOW_ENV=dev" >> $GITHUB_ENV

      - name: Set production environment
        if: ${{ github.ref_name == 'main' }}
        run: |
          echo "FLOW_ENV=prod" >> $GITHUB_ENV

      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v1

      - name: Install python packages
        uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt

      - name: Raw Verra data
        run: scripts/flow_prefect_deployment.sh raw_verra_data --interval 86400 --anchor-date 2023-05-18T12:35:00.000000+02:00

      - name: Clean up old artifact
        run: scripts/flow_prefect_deployment.sh clean_up_old_artifacts --interval 86400 --anchor-date 2023-05-18T10:05:00.000000+02:00
